# Generated by Django 3.0.2 on 2020-04-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.URLField(null=True, unique=True),
        ),
    ]
