# Generated by Django 3.0.2 on 2020-07-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_entryinteraction_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryinteraction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
